package com.pkrss.voicespeakking.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.pkrss.voicespeakking.db.model.SpeakItem;

import com.pkrss.voicespeakking.db.dao.SpeakItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig speakItemDaoConfig;

    private final SpeakItemDao speakItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        speakItemDaoConfig = daoConfigMap.get(SpeakItemDao.class).clone();
        speakItemDaoConfig.initIdentityScope(type);

        speakItemDao = new SpeakItemDao(speakItemDaoConfig, this);

        registerDao(SpeakItem.class, speakItemDao);
    }
    
    public void clear() {
        speakItemDaoConfig.getIdentityScope().clear();
    }

    public SpeakItemDao getSpeakItemDao() {
        return speakItemDao;
    }

}
